/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import DomainModel.AracKiralama;
import DomainModel.Register;
import DomainModel.Sube;
import DomainModel.Tarih;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Baransel
 */
public class AracKiralamaEkran extends javax.swing.JFrame {
    Register register = MainCenter.register;
    DefaultComboBoxModel<String> modelAlisTarih,modelTeslimTarih;
    DefaultComboBoxModel<String> modelAlisSube,modelTeslimSube;
    String[] subeler;
    String[] tarihler;
    public AracKiralamaEkran() {
        subeleriAl();
        tarihleriAl();
        modelAlisTarih = new DefaultComboBoxModel<>(tarihler);
        modelTeslimTarih = new DefaultComboBoxModel<>(tarihler);
        modelAlisSube = new DefaultComboBoxModel<>(subeler);
        modelTeslimSube = new DefaultComboBoxModel<>(subeler);
        initComponents();
        lblHosgeldiniz.setText("Hoşgeldiniz " + Musteri.musteri.getIsim() + " " + Musteri.musteri.getSoyisim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHosgeldiniz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(418, 300));
        setResizable(false);

        lblHosgeldiniz.setText("Hoşgeldiniz Bilmem KİM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHosgeldiniz)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHosgeldiniz)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void subeleriAl() {
        subeler = new String[register.subeCatalog.getSubeler().size()];
        for (int i = 0;i<subeler.length;i++) {
            subeler[i] = register.subeCatalog.getSubeler().get(i).getSubeAdi();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AracKiralamaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHosgeldiniz;
    // End of variables declaration//GEN-END:variables

    private void tarihleriAl() {
        tarihler = new String[120];
        int gun = LocalDate.now().getDayOfMonth();
        int ay = LocalDate.now().getMonthValue();
        int yil = LocalDate.now().getYear();
        Tarih tarih = new Tarih(gun, ay, yil);
        
        for(int i = 0;i<tarihler.length;i++) {
            tarih.tarihArttir(1);
            tarihler[i] = tarih.tarihYaz();
        }   
    }
}
